name: world_travel
description: "world_travel"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1
  flutter: 3.29.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.1
  go_router_builder: ^2.7.5
  flutter_hooks: ^0.21.0
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  formz: ^0.8.0
  firebase_auth: ^5.5.1

  # For pinCode
  pin_code_fields: 8.0.1

  # For Firebase
  firebase_core: 3.12.1
  firebase_messaging: 15.2.4
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4
  firebase_remote_config: ^5.4.2
  flutter_local_notifications: ^19.0.0
  rive: ^0.13.20 # 現状cocoaPodsに依存。SPMに変更されたらバージョンアップしてcocoaPodsを削除する
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.2
  native_dio_adapter: ^1.4.0
  shared_preferences: ^2.5.2

  # For url_launcher
  url_launcher: ^6.3.1

  # For app info and device info
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3

  collection: ^1.19.1
  file_picker: ^9.0.2
  mime: ^2.0.0
  material_symbols_icons: ^4.2805.1
  webview_flutter: ^4.0.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  riverpod_generator: ^2.6.4
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  very_good_analysis: ^7.0.0
  widgetbook: ^3.7.1
  widgetbook_generator: ^3.7.0
  alchemist: ^0.11.0
  firebase_auth_mocks: ^0.14.1

flutter:
  uses-material-design: true
